#This Dockerfile helps to provide an image for an ARM64 system 
#under dotnet SDK version 8. 
#E.g. for a Raspberry PI 4 under Raspberry PI OS.
#For example, the Dockerfile was successfully tested with an asp.net C# web API.

#FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/aspnet:8.0 AS base
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8


#FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/sdk:8.0 AS build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MySite.csproj", "MySite/"]
RUN dotnet restore "./MySite/MySite.csproj"

COPY ["*", "MySite/"]
WORKDIR "/src/MySite"
RUN dotnet build "MySite.csproj" -c Release -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "MySite.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MySite.dll"]