// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MySite.Models;

public partial class ResumeLogin
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Pwhash { get; set; }
}