// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MySite.Models;

public partial class ResumeLifestage
{
    public int Id { get; set; }

    public string LifestageTitle { get; set; }

    public short? Order { get; set; }
}